image: docker.inventale.com/platform/build/jdk/jdk11:1.1.6

stages:
  - verify

before_script:
  #  cache gradle for the branch
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: rest-assured-one-key-to-rule-them-all
  paths:
    - .gradle/wrapper
    - .gradle/caches

# --------- Verify stage ---------
it:
  stage: verify
  script:
    - ./gradlew clean integrationTest
  artifacts:
    expire_in: 3 days
    when: always
    name: "$CI_BUILD_ID"
    paths:
      - gradle.log
      - $CI_PROJECT_DIR/**/build/*
    reports:
      junit: $CI_PROJECT_DIR/**/build/test-results/*/TEST-*.xml
  only:
    variables:
      - $RUN_IT
